### PR TITLE
phpbrew v2+ doesn't work with PHP 8.2+ but the last version of PHPBrew v1.28.0 seems to work

### PR DESCRIPTION
**Pull request by chrispelzer**
PHP 8.2 isn't supported with PHPBrew v2+ but works with PHPBrew v1.28.0
https://github.com/phpbrew/phpbrew/issues/1345

### CODE REVIEW

**Comment by pgporada** [comment]
This is an issue because base started using php 8.2.x within the past 2 weeks https://github.com/waynestate/base-site/blob/c42887f9939e9f214f6e379422bd784db9e63008/.phpbrewrc

**Comment by chrispelzer** [comment]
Yea, Nick updated it to Laravel v10 which requires PHP 8.1+ but we only have PHP 8.0 or PHP 8.2 options with our servers

**Comment by pgporada** [comment]
@chrispelzer Can you file an issue here to upgrade to phpbrew 2.x please?

**Comment by chrispelzer** [comment]
> @chrispelzer Can you file an issue here to upgrade to phpbrew 2.x please?

done https://github.com/pgporada/wsu-base-site-docker/issues/3

**Pull request merged**
